spring.application.name=identityservice
server.port=8096

app.secret-key=secure-key-12345

eureka.client.serviceUrl.defaultZone=http://${eureka.security.username}:${eureka.security.password}@localhost:8761/eureka/

eureka.security.username=switchUser
eureka.security.password=password123